au BufNewFile,BufRead *.s,*.S set filetype=arm " arm = armv6/7
set backspace=indent,eol,start

set nocompatible
syntax on
set showmode
set showcmd
set mouse=a
set encoding=utf-8
set t_Co=256
filetype indent on

set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

set number
set cursorline
set wrap
set linebreak
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set ruler

set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase

set undofile
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//
set undodir=~/.vim/.undo//
set autochdir
set history=1000
set autoread
set wildmenu
set wildmode=longest:list,full
